### ISSUE TITLE
No kotlin

### ISSUE THREAD

**Issue by kiritodragneel** [widavies/VocalCord#2]
I can't seem to get this to work without kotlin. 
Is there any reason you are using that as I would prefer not to 

and would you be able to make or help me get a version that does not use it

**Comment by widavies** [comment]
@kiritodragneel Yeah, there was a class that used Kotlin. I switched it to Java in the latest commit. Everything is Java now, so you should just be able to copy all the Java files verbatim. Let me know if you need anything else.
