### ISSUE TITLE
Only sleeping

### ISSUE THREAD

**Issue by kiritodragneel** [widavies/VocalCord#3]
I have coppied the code exactly apart from how to activate which I have showed below, however I only get "...sleeping" never wakes however much i scream at it.

I also have put the json from the google key in the vocalcord folder. 

	public command() {
		this.name = "talk";
		this.help = "DOES TALKING SHIT";
		this.userPermissions = new Permission[] {Permission.ADMINISTRATOR};
	}

	@Override
	protected void execute(CommandEvent event) {
		Guild guild = event.getGuild();
		VoiceChannel voiceroom = guild.getVoiceChannelById(event.getMember().getVoiceState().getAudioChannel().getId());

		AudioManager manager = guild.getAudioManager();
		manager.setSendingHandler(new SilenceAudioSendHandler());
		SpeechReceiver speechReceiver = new SpeechReceiver("yo bought", new SpeechCallback() {

			@Override
			public void commandReceived(String command) {
				if (!command.equals(""))
					event.getChannel().sendMessage("You said: " + command + ". Is that right?").queue();
			}

			@Override
			public boolean botAwakeRequest(User... user) {
				System.out.println("Bot awakened!");
				return false;
			}
		});

		speechReceiver.setCombinedAudio(true);
		manager.setReceivingHandler(speechReceiver);
		manager.openAudioConnection(voiceroom);
	}

}

**Comment by kiritodragneel** [comment]
any help plzz

**Comment by Pyragon** [comment]
Try returning true in botAwakeRequest

**Comment by widavies** [comment]
Sorry didn't see this, will take a look when I get a chance.

**Comment by Jonbeckas** [comment]
I have the same problem by copiing the code from the example

**Comment by widavies** [comment]
@kiritodragneel are you getting a bot awake request ?

**Comment by beatzzz** [comment]
I sent you a email @wdavies973

**Comment by beatzzz** [comment]
Does the api work right now?

**Comment by widavies** [comment]
It should

**Comment by widavies** [comment]
@kiritodragneel @Pyragon @Jonbeckas Just updated, completely redesigned the library.
