### ISSUE TITLE
Done talking callback

### ISSUE THREAD

**Issue by Goopher** [widavies/VocalCord#7]
Hello,

I was wondering if there is some sort of callback for when the TTS is done talking?
My use case would be: 

I execute command, bot connects to voice channel, bot says TTS, bot is done, bot disconnects from voice channel.

I checked the source and docs but can't currently find an option for such a callback.

**Comment by widavies** [comment]
@Goopher Added the callback, let me know if you have any questions on how to get it working. All you should need to do is override the "onTTSCompleted(..)" method in your VocalCord interface implementation.

**Comment by Goopher** [comment]
@wdavies973 Works perfectly fine, thanks!
